import type { Metadata, Viewport } from "next";
import "./globals.css";
//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Api Catalog",
  description: "Generated by AmirNaderi",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-icon.png" />
        <meta name="theme-color" content="#fff" />
      </head>
      <body className="max-h-screen">
        {children}
      </body>
    </html>
  );
}
