import type { Metadata } from "next";
import "./globals.css";
//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Api Catalog",
  description: "Generated by AmirNaderi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-icon.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#fff" />
      </head>
      <body className="max-h-screen">{children}</body>
    </html>
  );
}
